services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: lazy_baker
      POSTGRES_USER: lazy_baker
      POSTGRES_PASSWORD: lazy_baker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
