# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0003_auto_20170822_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.RecipePage'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
    ]
