# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0004_auto_20170822_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(blank=True, max_length=127)),
                ('github_username', models.CharField(blank=True, max_length=127)),
                ('instagram_username', models.CharField(blank=True, max_length=127)),
                ('linkedin_url', models.CharField(blank=True, help_text='This is the part after the /in/ on the address of your profile', max_length=127)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='google_custom_search_key',
        ),
    ]
