# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170822_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Social media accounts'},
        ),
    ]
