# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170822_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_author',
            field=models.CharField(blank=True, help_text='Claim credit', max_length=127),
        ),
    ]
