# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('home', '0009_headericon'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_icon',
            field=models.ForeignKey(help_text='This should be a square line-based icon in the right color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(blank=True, help_text='This text will be formatted with markdown.'),
        ),
    ]
