# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('home', '0010_auto_20170824_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='recipe_icon',
            field=models.ForeignKey(help_text='This should be a square line-based icon in the right color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
