# Generated by Django 2.2.8 on 2020-01-07 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190902_0232'),
        ('home', '0013_generalsettings_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.CustomImage'),
        ),
        migrations.DeleteModel(
            name='HeaderIcon',
        ),
    ]
