# Generated by Django 2.2.8 on 2020-03-01 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0014_auto_20200107_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='random_recipe_category',
            field=models.ForeignKey(blank=True, help_text='Which Category will random recipes be selected from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
