# Generated by Django 2.2.8 on 2020-03-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_generalsettings_random_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='random_recipe_category',
            field=models.ForeignKey(blank=True, help_text='Which Category will random recipes be selected from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.CategoryPage'),
        ),
    ]
