# Generated by Django 2.2.8 on 2020-03-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190902_0232'),
        ('home', '0016_auto_20200301_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='random_recipe_icon',
            field=models.ForeignKey(blank=True, help_text='This should be a square line-based icon in the right color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
