# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20170822_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryindexpage',
            options={'verbose_name': 'Recipe Categories Index'},
        ),
        migrations.AlterModelOptions(
            name='recipeindexpage',
            options={'verbose_name': 'Recipes Index'},
        ),
        migrations.RemoveField(
            model_name='recipeindexpage',
            name='intro',
        ),
    ]
