# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20170822_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=128)),
                ('ingredient', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('instruction', models.TextField()),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='body',
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_categories', to='recipes.RecipePage'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='intro',
            field=models.TextField(help_text='Appears above the recipe and on preview pages. This text will be formatted with markdown.', max_length=250),
        ),
        migrations.AddField(
            model_name='instruction',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.RecipePage'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.RecipePage'),
        ),
    ]
