# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170822_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=models.TextField(verbose_name=''),
        ),
    ]
