# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20170822_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='date',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='servings',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
