# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20170822_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prep time (min.)'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prep time (min.)'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
    ]
