# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20170823_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='post_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=models.TextField(help_text='This text will be formatted with markdown.', verbose_name=''),
        ),
    ]
