# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('recipes', '0008_auto_20170823_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='icon',
            field=models.ForeignKey(help_text='This should be a square line-based icon in the right color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='total_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total time (min.)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='cook_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cook time (min.)'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='main_image',
            field=models.ForeignKey(help_text='Image should be at least 1280x416 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
