# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20170823_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='page',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='ingredients',
            field=models.TextField(blank=True, help_text='One ingredient per line. Make separate sections with a square bracketed line like [section name]. This text will be formatted with markdown.'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
