# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipepage_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='total_time',
        ),
    ]
