# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipepage_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='cook_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='prep_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
