# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20170824_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='cook_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='prep_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
