# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20170824_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='page',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='instructions',
            field=models.TextField(blank=True, help_text='Each new line generates a new numbered instruction. This text will be formatted with markdown.'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes such as substitutions. This text will be formatted with markdown.'),
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
