# Generated by Django 2.2.4 on 2019-09-02 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20170824_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.CategoryPage'),
        ),
    ]
