# Generated by Django 2.2.8 on 2020-01-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20190902_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypage',
            options={'ordering': ['title'], 'verbose_name': 'Category'},
        ),
    ]
